name: Generate POT file
on:
  push:
    branches:
      - develop

jobs:
  WP_Generate_POT_File:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WordPress .pot File Generator
      uses: iamdharmesh/action-wordpress-pot-generator@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}