name: Generate POT file
on:
  push:
    branches:
      - develop

jobs:
  WP_Generate_POT_File:
    runs-on: ubuntu-latest
    steps:
    - run: git --version # 2.35.1
    - uses: actions/checkout@v2
    - name: WordPress .pot File Generator
    - run: export GIT_CEILING_DIRECTORIES=/__w # only work before git v2.35.2
      uses: iamdharmesh/action-wordpress-pot-generator@main
      with:
        destination_path: './languages'
        text_domain: 'oiga'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}