name: Generate POT file
on:
  push:
    branches:
      - develop

jobs:
  WP_Generate_POT_File:
    runs-on: ubuntu-latest
    steps:
    - run: sudo git config --global safe.directory "$GITHUB_WORKSPACE"
    - uses: actions/checkout@v2
    - name: WordPress .pot File Generator
      uses: iamdharmesh/action-wordpress-pot-generator@main
      with:
        destination_path: './languages'
        text_domain: 'oiga'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}