- name: WordPress Vulnerability Check
  # You may pin to the exact commit or the version.
  # uses: umutphp/wp-vulnerability-check-github-action@436c0d50399b71836f526aa03bcbdac46aa966ac
  uses: umutphp/wp-vulnerability-check-github-action@v18
  with:
    # Root path of your WordPress installation
    path: 
    # Token got from wpvulndb.com
    token: 
    # Root path of plugins if it is different than default
    pluginPath: # optional, default is ./wp-content/plugins/
    # Root path ofmu-plugins if it is different than default
    MUpluginPath: # optional, default is ./wp-content/mu-plugins/
    # The plugins to be excluded. In order to exclude your custom plugins
    exclude: # optional, default is verycustomplugin
