name: Compile Language Files
on:
  push:
    branches:
      - develop
      - v1.0.0

jobs:
  WP_Generate_POT_File:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      uses: odil-io/action-compile-language-files@latest
      with:
        destination_path: './languages'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
